name = "MyFirstPackage"
uuid = "a304e98c-866b-4fb6-a799-e59ed0e3fc60"
authors = ["Matt Landreman"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
